/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniteRouteImport } from './routes/unite'
import { Route as TopScorerRouteImport } from './routes/top-scorer'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReglementRouteImport } from './routes/reglement'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UniteMatchsRouteImport } from './routes/unite.matchs'
import { Route as UniteLoginRouteImport } from './routes/unite.login'
import { Route as UniteGestionRouteImport } from './routes/unite.gestion'
import { Route as UniteClassementRouteImport } from './routes/unite.classement'
import { Route as ApiPublicHooksSyncScoresRouteImport } from './routes/api/public/hooks/sync-scores'

const UniteRoute = UniteRouteImport.update({
  id: '/unite',
  path: '/unite',
  getParentRoute: () => rootRouteImport,
} as any)
const TopScorerRoute = TopScorerRouteImport.update({
  id: '/top-scorer',
  path: '/top-scorer',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglementRoute = ReglementRouteImport.update({
  id: '/reglement',
  path: '/reglement',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniteMatchsRoute = UniteMatchsRouteImport.update({
  id: '/matchs',
  path: '/matchs',
  getParentRoute: () => UniteRoute,
} as any)
const UniteLoginRoute = UniteLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UniteRoute,
} as any)
const UniteGestionRoute = UniteGestionRouteImport.update({
  id: '/gestion',
  path: '/gestion',
  getParentRoute: () => UniteRoute,
} as any)
const UniteClassementRoute = UniteClassementRouteImport.update({
  id: '/classement',
  path: '/classement',
  getParentRoute: () => UniteRoute,
} as any)
const ApiPublicHooksSyncScoresRoute =
  ApiPublicHooksSyncScoresRouteImport.update({
    id: '/api/public/hooks/sync-scores',
    path: '/api/public/hooks/sync-scores',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/reglement': typeof ReglementRoute
  '/reset-password': typeof ResetPasswordRoute
  '/top-scorer': typeof TopScorerRoute
  '/unite': typeof UniteRouteWithChildren
  '/unite/classement': typeof UniteClassementRoute
  '/unite/gestion': typeof UniteGestionRoute
  '/unite/login': typeof UniteLoginRoute
  '/unite/matchs': typeof UniteMatchsRoute
  '/api/public/hooks/sync-scores': typeof ApiPublicHooksSyncScoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/reglement': typeof ReglementRoute
  '/reset-password': typeof ResetPasswordRoute
  '/top-scorer': typeof TopScorerRoute
  '/unite': typeof UniteRouteWithChildren
  '/unite/classement': typeof UniteClassementRoute
  '/unite/gestion': typeof UniteGestionRoute
  '/unite/login': typeof UniteLoginRoute
  '/unite/matchs': typeof UniteMatchsRoute
  '/api/public/hooks/sync-scores': typeof ApiPublicHooksSyncScoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/reglement': typeof ReglementRoute
  '/reset-password': typeof ResetPasswordRoute
  '/top-scorer': typeof TopScorerRoute
  '/unite': typeof UniteRouteWithChildren
  '/unite/classement': typeof UniteClassementRoute
  '/unite/gestion': typeof UniteGestionRoute
  '/unite/login': typeof UniteLoginRoute
  '/unite/matchs': typeof UniteMatchsRoute
  '/api/public/hooks/sync-scores': typeof ApiPublicHooksSyncScoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/leaderboard'
    | '/matches'
    | '/profile'
    | '/reglement'
    | '/reset-password'
    | '/top-scorer'
    | '/unite'
    | '/unite/classement'
    | '/unite/gestion'
    | '/unite/login'
    | '/unite/matchs'
    | '/api/public/hooks/sync-scores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/leaderboard'
    | '/matches'
    | '/profile'
    | '/reglement'
    | '/reset-password'
    | '/top-scorer'
    | '/unite'
    | '/unite/classement'
    | '/unite/gestion'
    | '/unite/login'
    | '/unite/matchs'
    | '/api/public/hooks/sync-scores'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/leaderboard'
    | '/matches'
    | '/profile'
    | '/reglement'
    | '/reset-password'
    | '/top-scorer'
    | '/unite'
    | '/unite/classement'
    | '/unite/gestion'
    | '/unite/login'
    | '/unite/matchs'
    | '/api/public/hooks/sync-scores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MatchesRoute: typeof MatchesRoute
  ProfileRoute: typeof ProfileRoute
  ReglementRoute: typeof ReglementRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TopScorerRoute: typeof TopScorerRoute
  UniteRoute: typeof UniteRouteWithChildren
  ApiPublicHooksSyncScoresRoute: typeof ApiPublicHooksSyncScoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unite': {
      id: '/unite'
      path: '/unite'
      fullPath: '/unite'
      preLoaderRoute: typeof UniteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-scorer': {
      id: '/top-scorer'
      path: '/top-scorer'
      fullPath: '/top-scorer'
      preLoaderRoute: typeof TopScorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglement': {
      id: '/reglement'
      path: '/reglement'
      fullPath: '/reglement'
      preLoaderRoute: typeof ReglementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unite/matchs': {
      id: '/unite/matchs'
      path: '/matchs'
      fullPath: '/unite/matchs'
      preLoaderRoute: typeof UniteMatchsRouteImport
      parentRoute: typeof UniteRoute
    }
    '/unite/login': {
      id: '/unite/login'
      path: '/login'
      fullPath: '/unite/login'
      preLoaderRoute: typeof UniteLoginRouteImport
      parentRoute: typeof UniteRoute
    }
    '/unite/gestion': {
      id: '/unite/gestion'
      path: '/gestion'
      fullPath: '/unite/gestion'
      preLoaderRoute: typeof UniteGestionRouteImport
      parentRoute: typeof UniteRoute
    }
    '/unite/classement': {
      id: '/unite/classement'
      path: '/classement'
      fullPath: '/unite/classement'
      preLoaderRoute: typeof UniteClassementRouteImport
      parentRoute: typeof UniteRoute
    }
    '/api/public/hooks/sync-scores': {
      id: '/api/public/hooks/sync-scores'
      path: '/api/public/hooks/sync-scores'
      fullPath: '/api/public/hooks/sync-scores'
      preLoaderRoute: typeof ApiPublicHooksSyncScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface UniteRouteChildren {
  UniteClassementRoute: typeof UniteClassementRoute
  UniteGestionRoute: typeof UniteGestionRoute
  UniteLoginRoute: typeof UniteLoginRoute
  UniteMatchsRoute: typeof UniteMatchsRoute
}

const UniteRouteChildren: UniteRouteChildren = {
  UniteClassementRoute: UniteClassementRoute,
  UniteGestionRoute: UniteGestionRoute,
  UniteLoginRoute: UniteLoginRoute,
  UniteMatchsRoute: UniteMatchsRoute,
}

const UniteRouteWithChildren = UniteRoute._addFileChildren(UniteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  LeaderboardRoute: LeaderboardRoute,
  MatchesRoute: MatchesRoute,
  ProfileRoute: ProfileRoute,
  ReglementRoute: ReglementRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TopScorerRoute: TopScorerRoute,
  UniteRoute: UniteRouteWithChildren,
  ApiPublicHooksSyncScoresRoute: ApiPublicHooksSyncScoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
